sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: dzr3bXqKmJPxC6nYwHcM6hGGeAG1vMbY39h6Kdu52efnoiN7IKLATPIHntQExibk5HgHg9fL/pHPHxxAe9h1uFDPA50NxebtHCfQYRy288uisc8knJuRP4rwgptMFzDH9Qv3wVb4wHwksTEiWAji9BY3uFauaF5aSPMiYIhAK93IzVYwyBXESRMWp/Xr9AeY9PfRIf3ApTbjLb28FlBrrfO1nFYGPN6UvPuckCkYggv5HT6fZHS1582iXAgptfq3DZHBMchgd7E+BJGJvpjNYatZTto5H8u+pwhlbw+EX0+oKOMlfwEpxUvoVYofhYYZgKGzz3QRxU1KqXEwsoPuPpfcifzSC47lt9NvpY7+PW6UKpTWrtihz+2F0C+MYfAhwZL86q+wtViFJcd34HC2qj+IauGm0x00hL0mXyVLB2XSsKeizu44h0+VZyppUcJ1UqP90JhP084yL9cay5/MY1qvIfW8xy6nhPELpIB3vNhgCdDbx9VeaOVEzGrZ7v1fJxip36MkwZdeQ4j23yN6GPrnNlybIM7iPFmMR+wIWq4YUOtzSXpvNXgX+eZz8k8V7aCBHiRSsH82RTlwl+iIz7FJD5zH+DCOjsZr5MpUosweEDP3bTMiCwpd78vOvX7zKa6Rz3dJK0wxsfcumlYxx2jBtHgAVp0fTpYozOpGP2k=
    - secure: cU8nb4PUSdP0jb1m6JuYT+TP900migYPeY0F90XhAzU5X3C4Zm8ewQmNhx7T/UH6p53C37dqUzBX36Q0ET/SUu8ge3q9MqaktkqlT6srGyb8xz1a5A2RICum+SLOrJhpp+OC/kV2C31fst0bVbxPXYrrVJPnwbe83JebYz0WnwGdQqw/2KVHfF5VmQYjmTt3+Y0Cafryuqd8b12Xw5trriPhooi2hhTa+lx5AnX+Ef8znLSpyZo/JdRWt+wDkFHk2QGXY8qZnueU3VvSNuYRT7weSfbcs5+E62aYeQOYNjaggtnIkMAgnMWsCiCQSFjJJ+yApCnJdD0nWJuGkc/WpyeQVBVHsC5IPiyOplttqWehSV691yo0lkxdj0WsZdus+fvxG09jcDz774O3ZB4GyemiPkXeKpS65Lf5CjJ/JuRWYbxcadA3l9RWmukUXxX7RJjw3RZIb352aW0UCY9P1boFvxJofAx5PFPyNyBxdknnxC3A3z+u+8Wrs7LtO+1+wZB8quTkrIdhQBvbPyjyDgQu+ce3Gkbqnvd3Y9oF71eiIrnhMpfD1BEFuhSmbtF5HsaBWV7YHwS9AJnxbXGGgUNpfvwkiCUoeD8wG6VoS+LL3v25ANjWeBJPv0gZlKJ+DE++lovTwvypVYocvI4aDvgGgZUGn73dpmvPdxM10Fs=
